#!/bin/bash

echo Creating raw-data folder ...
mkdir raw-data
echo Downloading dataset ...
wget https://transfer.sh/DlKHo/pic-parser-best.weights -O raw-data/model.weights
echo Creating cleaned-data folder ...
mkdir cleaned-data
echo Downloading dataset ...
wget https://transfer.sh/DlKHo/pic-parser-best.weights -O cleaned-data/model.weights
